export interface RaceResult {
  rank: string | null;
  swimmer_name: string | null;
  school_name: string | null;
  entry_group_name1: string | null;
  entry_group_name2: string | null;
  entry_group_name3: string | null;
  result_time: string | null;
  reaction_time: string | null;
  lap25: string | null;
  lap50: string | null;
  lap75: string | null;
  lap100: string | null;
  lap125: string | null;
  lap150: string | null;
  lap175: string | null;
  lap200: string | null;
  heat: string | null;
  game_code: string | null;
  program_id: string | null;
  display_program_id: string | null;
  swimming_style_code: string | null;
  swimming_style_name: string | null;
  distance: string | null;
  distance_name: string | null;
  race_division_name: string | null;
  gender_code: string | null;
  gender_name: string | null;
  class_name: string | null;
  game_date: string | null;
  race_status: string | null;
  is_finished: boolean | null;
  has_reaction_time: boolean | null;
  has_lap_time: boolean | null;
}

export function parseRaceResults(data: any[]): RaceResult[] {
  return data.map((entry: any) => ({
    rank: entry.rank ?? null,
    swimmer_name: entry.swimmer_name ?? null,
    school_name: entry.school_name ?? null,
    entry_group_name1: entry.entry_group_name1 ?? null,
    entry_group_name2: entry.entry_group_name2 ?? null,
    entry_group_name3: entry.entry_group_name3 ?? null,
    result_time: entry.result_time ?? null,
    reaction_time: entry.reaction_time ?? null,
    lap25: entry.lap25 ?? null,
    lap50: entry.lap50 ?? null,
    lap75: entry.lap75 ?? null,
    lap100: entry.lap100 ?? null,
    lap125: entry.lap125 ?? null,
    lap150: entry.lap150 ?? null,
    lap175: entry.lap175 ?? null,
    lap200: entry.lap200 ?? null,
    heat: entry.heat ?? null,
    game_code: entry.game_code ?? null,
    program_id: entry.program_id ?? null,
    display_program_id: entry.display_program_id ?? null,
    swimming_style_code: entry.swimming_style_code ?? null,
    swimming_style_name: entry.swimming_style_name ?? null,
    distance: entry.distance ?? null,
    distance_name: entry.distance_name ?? null,
    race_division_name: entry.race_division_name ?? null,
    gender_code: entry.gender_code ?? null,
    gender_name: entry.gender_name ?? null,
    class_name: entry.class_name ?? null,
    game_date: entry.race_date ?? null,
    race_status: entry.race_status ?? null,
    is_finished: entry.is_finished ?? null,
    has_reaction_time: entry.has_reaction_time ?? null,
    has_lap_time: entry.has_lap_time ?? null
  }));
}
